# DB disk
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk0001
    fsType: ext4
--
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001
  labels:
    app: fonoster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
