# Media files
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.142.0.5
    path: '/mnt/disk0002'
--
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0002
  labels:
    app: fonoster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
