apiVersion: v1
kind: Service
metadata:
  name: datasys
  labels:
    app: fonoster
spec:
  ports:
    - port: 27017
  selector:
    app: fonoster
    tier: data
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datasys
  labels:
    app: fonoster
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fonoster
        tier: data
    spec:
      containers:
      - name: fndb
        image: gcr.io/fonoster-app/fndb:latest
        imagePullPolicy: Always
        env:
        - name: FONOSTER_ENV
          value: prod               # If set to dev it will bootstrap with some basic data
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc0001
