apiVersion: v1
kind: Service
metadata:
  name: mediaserver
  labels:
    app: fonoster
spec:
  ports:
  - name: sip
    port: 5060
  selector:
    app: fonoster
    tier: media
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mediaserver
  labels:
    app: fonoster
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fonoster
        tier: media
    spec:
      containers:
      - name: fnvoiceapps
        image: gcr.io/fonoster-app/fnvoiceapps:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: datasys
        ports:
        - containerPort: 4573
          name: fastagi
        volumeMounts:
        - name: pd
          mountPath: /var/lib/fonoster
      - name: fnasterisk
        image: gcr.io/fonoster-app/fnasterisk:latest
        imagePullPolicy: Always
        env:
        - name: EXTERN_ADDR
          value: 104.196.160.85:5060
        - name: LOCALNET
          value: 10.0.0.0/32
        ports:
        - containerPort: 5038
          name: ami
        - containerPort: 5060
          name: sip
        volumeMounts:
        - name: pd
          mountPath: /var/lib/fonoster
      volumes:
      - name: pd
        persistentVolumeClaim:
          claimName: pvc0002